### ISSUE TITLE
Implement basic denial-of-service resistence

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#12]
Implement some basic checks on the resources invoked when receiving messages.

```[tasklist]
### Tasks
- [x] Minimise work done validating or storing equivocating messages from one sender
- [x] Detect and ignore semantically-duplicate messages
- [x] https://github.com/filecoin-project/go-f3/issues/169
- [x] https://github.com/filecoin-project/go-f3/issues/153
- [x] https://github.com/filecoin-project/go-f3/issues/240
- [x] https://github.com/filecoin-project/go-f3/issues/151
- [x] drop messages from old rounds and phases that have already passed
- [x] #208
- [ ] #303
```

```[tasklist]
### Tasks
```

**Comment by Stebalien** [comment]
Also, should we drop messages from old rounds and phases that have already passed?

**Comment by anorth** [comment]
> Also, should we drop messages from old rounds and phases that have already passed?

We could, but I don't think it's particularly worthwhile. Old _instances_ yes (already the case).

**Comment by anorth** [comment]
> Also, should we drop messages from old rounds and phases that have already passed?

Done for QUALITY, CONVERGE, and PREPARE. The COMMIT phase stays open, and a message can still cause a decision even if the node moved on.

**Comment by anorth** [comment]
>  Minimise work done validating or storing equivocating messages from one sender
> Detect and ignore semantically-duplicate messages

The quorum state for each step maintains a set of senders, and ignores anything after the first message for that (sender, step).

**Comment by anorth** [comment]
I think this is complete after #208.

- With only one message per (sender, round, phase) retained or causing any state allocation, work is limited to what can be received
- Since almost all messages require justification from 2/3 of power, that state or work is limited to relatively small amounts, and reflecting actual protocol progress
- Messages that do not require justification are QUALITY (only valid with round zero) and COMMIT for bottom. These latter are limited to a configurable number of rounds ahead of present.
- As of #300, I believe we don't allocate any state for dropped messages

I briefly looked through all other slices and maps in participant/instance state, and believe them all to be limited either concretely or by assumptions (e.g. size of power table is practically limited well below DOS values, number of rounds is limited by time taken for 2/3 of power to progress, number of instance committees is a configured value)

**Comment by jennijuju** [comment]
as #208 is merged can i close this issue?
