### ISSUE TITLE
Implement changes from 1st protocol audit

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#170]
See FIP PR https://github.com/filecoin-project/FIPs/pull/985

```[tasklist]
### Tasks
- [x] Replace ECCompatibleChains with `C` (give a better name) which is updated when node observes a value that could have been decided by another participant
- [x] Remove the ECUpdate (`ReceiveAcceptable`) method
- [x] Implement might-have-been-decided predicate (replaced with strong-quorum-of-bottom check)
- [x] Require evidence for PREPARE when round > 0
- [x] Carefully check the message validation and justification methods match spec
- [x] Carefully check for other changes to the protocol pseudocode such as timeouts, thresholds etc
- [x] Implement #136
```
