### ISSUE TITLE
Design questions left for FIP 

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/go-f3#177]
Left design questions, only to be marked as done once they are in a PR for the FIP at least. 
```[tasklist]
### Tasks
- [x] 1. GossiPBFT message rebroadcast #169
- [x] 2. When to pull certificates and FEP #176 & [design doc, (not sure if deprecated)](https://docs.google.com/document/d/10i9tFremOSrZou9oO5A5wvu1uOy1lvFKbv8IsvoglR0/edit#heading=h.g8nngox3auow)
- [x] 3. When to start an f3 instance and offset head input chain #173 #175
- [x] 4. Offsetting power table #151
- [x] 5. Tipset struct representation #166
- [ ] 6. Finish off test cases in FIP
```

**Comment by ranchalp** [comment]
2. and 4. added to the following [Draft PR ](https://github.com/filecoin-project/FIPs/pull/996)

**Comment by ranchalp** [comment]
For ii. what is the state of the @Stebalien @Kubuxu ?

**Comment by jsoares** [comment]
Talked to @Kubuxu; let's wait until early next week and see if @Stebalien is back; if not, @Kubuxu will pick up 2 (FDEP) and 5 (ECTipset format).

**Comment by ranchalp** [comment]
i. is optimistically submitted to a [dedicated Draft PR](https://github.com/filecoin-project/FIPs/pull/998) but discussion is still open.

**Comment by jennijuju** [comment]
@anorth @masih can we do a ✅ practice to see whats left to do, i assume that determines when we can move FIP to last call?

**Comment by masih** [comment]
I am not sure about task No. 6 `Finish off test cases in FIP`, but the remaining subtasks seem to be implementation related not FIP related? 

Should the FIP go as far as documenting when to start an instance or pull certificates? They seem to be more on the implementation side than algorithmic part. Perhaps a paragraph on suggestions would suffice if the concensus is that the FIP should include them.

Apart from that I think the FIP could move to last call, unless there is something that I have missed.

@anorth  thoughts?

**Comment by anorth** [comment]
Yeah I think we're almost done with these design questions. I think it would be appropriate for the FIP to mention something about when to pull certificates, although I agree the policy is largely up to the client.

I would still be a bit hesitant to say the FIP is ready for last call right now, though. Things are still changing and we have yet to do a pass pushing implementation things back into the FIP - we need to be about done with implementation for that. We also have audits to review and I suspect we might find something there too.

**Comment by jsoares** [comment]
> we have yet to do a pass pushing implementation things back into the FIP - we need to be about done with implementation for that

That's not the bar we've been using in the FIP process. Core track FIPs only require an implementation to move from Accepted to Final, and many (most?) FIPs haven't even begun to be implemented before entering Last Call. There are frequent updates to the FIPs made after last call and even after acceptance as a result of implementation learnings -- to use recent examples, both FIP-0090 and FIP-0083 underwent substantive changes while marked as accepted. 

We can argue whether this is ideal or not, but there's no reason to diverge from practice in this particular case just because the implementation work is farther along than usual.
