### ISSUE TITLE
Implement protocol changes from FIP PR 996

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#192]
https://github.com/filecoin-project/FIPs/pull/996

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-f3/issues/121
- [x] Change backoff exponent to 2
- [x] Update any comments about the power table being for the base chain to be more abstractly about "the power table for this instance"
```

Most of the changes related to power table look back, don't apply in this repository, but to the integration in Lotus.
