### ISSUE TITLE
Comprehensive Simulation Testing

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-f3#226]
Conduct extensive simulation tests covering a comprehensive set of scenarios. Include test cases [from F3 FIP](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0086.md#test-cases) and [relevant GitHub issues](https://github.com/filecoin-project/go-f3/issues?q=is:issue+is:open+label:testing) to ensure thorough testing.
```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-f3/pull/221
- [ ] https://github.com/filecoin-project/go-f3/pull/209
- [ ] https://github.com/filecoin-project/go-f3/pull/230
- [ ] https://github.com/filecoin-project/go-f3/issues/196
- [ ] https://github.com/filecoin-project/go-f3/issues/189
- [ ] https://github.com/filecoin-project/go-f3/issues/128
- [ ] https://github.com/filecoin-project/go-f3/issues/146
- [ ] https://github.com/filecoin-project/go-f3/issues/165
- [ ] https://github.com/filecoin-project/go-f3/issues/218
- [ ] https://github.com/filecoin-project/go-f3/issues/115
- [ ] https://github.com/filecoin-project/go-f3/issues/114
- [ ] https://github.com/filecoin-project/go-f3/pull/178
- [ ] https://github.com/filecoin-project/go-f3/pull/152
- [ ] https://github.com/filecoin-project/go-f3/pull/142
```
