### ISSUE TITLE
Final GPBFT protocol alignment with FIP

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#244]
Do a final fine-grained pass over the protocol specification in the FIP and the implemented code. Ensure the FIP and implementation code are aligned in all necessary details, and that the FIP is complete enough to be a specification for another implementation (e.g. in Forest/Rust).

Things to pay particular attention to:
- Predicates for completing steps
- Timeout semantics
- Message validation and justification
- Handling of equivocations and duplicated messages at every state update
```[tasklist]
### Tasks
- [x] Code: Switch to `mayHaveStrongQuorum(value, r-1, COMMIT, 1/3))` in tryConverge
- [x] Spec supplementary data.
- [x] Describe power lookback.
- [x] Specify power threshold and applicability of other EC filters on power table participation (consensus fault, fee debt, etc). See #346
- [x] Specify backoff when instance repeatedly decides base chain
- [ ] https://github.com/filecoin-project/FIPs/pull/1022
```

FIP work in https://github.com/filecoin-project/FIPs/pull/1022

**Comment by anorth** [comment]
FIP PR: https://github.com/filecoin-project/FIPs/pull/1022/
