### ISSUE TITLE
Epic: Protocol completeness

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#246]
This is a tracking issue for tasks required to reach core GPBFT protocol completeness. Lotus integration, finality certificates, and most testing are to be tracked in other epics.

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-f3/issues/33
- [ ] https://github.com/filecoin-project/go-f3/issues/151
- [ ] https://github.com/filecoin-project/go-f3/issues/240
- [ ] https://github.com/filecoin-project/go-f3/issues/241
- [ ] https://github.com/filecoin-project/go-f3/issues/242
- [ ] https://github.com/filecoin-project/go-f3/issues/243
- [ ] https://github.com/filecoin-project/go-f3/issues/245
- [ ] https://github.com/filecoin-project/go-f3/issues/12
- [ ] https://github.com/filecoin-project/go-f3/issues/9
- [ ] https://github.com/filecoin-project/go-f3/issues/255
- [ ] https://github.com/filecoin-project/go-f3/issues/173
- [ ] https://github.com/filecoin-project/go-f3/issues/244
- [ ] https://github.com/filecoin-project/go-f3/issues/175
```

**Comment by jennijuju** [comment]
@anorth i added #12 here lmk if thats not right
