### ISSUE TITLE
Epic: Finality Exchange Protocol

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#248]
**Success Criteria**: A client can safely "catch up" to the latest F3 instance.

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-f3/issues/5
- [ ] https://github.com/filecoin-project/go-f3/issues/14
- [ ] https://github.com/filecoin-project/go-f3/issues/15
- [ ] https://github.com/filecoin-project/go-f3/issues/405
- [ ] https://github.com/filecoin-project/go-f3/issues/247
```

**Comment by Stebalien** [comment]
There's one more issue, but that's not a part of milestone 0 so I'm closing this epic.
