### ISSUE TITLE
Epic: F3 Testing & Network Testing

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#249]
**Acceptance Criteria**
* Unit test code coverage of above 95% across core implementation packages.
* Component test for well known scenarios, e.g. quorum strength, power fluctuation, EC progress halt.
* Long running comprehensive simulation tests.
* End to end tests over local devnet

```[tasklist]
- [ ] https://github.com/filecoin-project/go-f3/issues/239
- [ ] https://github.com/filecoin-project/go-f3/issues/237
- [ ] https://github.com/filecoin-project/go-f3/issues/236
- [ ] https://github.com/filecoin-project/go-f3/issues/235
- [ ] https://github.com/filecoin-project/go-f3/issues/229
- [ ] https://github.com/filecoin-project/go-f3/issues/228
- [ ] https://github.com/filecoin-project/go-f3/issues/226
- [ ] https://github.com/filecoin-project/go-f3/issues/57
- [ ] https://github.com/filecoin-project/go-f3/issues/160
- [ ] https://github.com/filecoin-project/go-f3/issues/227
- [ ] https://github.com/filecoin-project/go-f3/issues/165
```

**Comment by rjan90** [comment]
@masih Can we get an updated check on which testing efforts are left to do here?

**Comment by masih** [comment]
The status of tickets listed in the description is up-to-date. Is there further information you are looking for?
