### ISSUE TITLE
Epic: Lotus integration

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#253]
**Acceptance criteria:**
- F3 runs within lotus using its libp2p stack
- Messages are propagated through pubsub
- Finality exchange over libp2p streams
- Lotus feeds chain information into F3
- F3 has a way to bootstrap

(WIP)

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-f3/issues/103
- [ ] https://github.com/filecoin-project/go-f3/issues/15
- [ ] #225
- [ ] https://github.com/filecoin-project/go-f3/issues/270
- [ ] https://github.com/filecoin-project/go-f3/issues/271
- [ ] https://github.com/filecoin-project/go-f3/issues/272
- [ ] https://github.com/filecoin-project/go-f3/issues/365
```

**Comment by jennijuju** [comment]
@Kubuxu question for you - how would the application fetch the finality / get a signal from lotus that  "we have reached finality for this epoch via 3"? Something new along with ChainHead (which only gives your the latest block w/o confirming it is finalized) ?

**Comment by Kubuxu** [comment]
I haven't thought about it a lot, but it seems reasonable, `ChainGetFinalizedHead` or something like that.

**Comment by Kubuxu** [comment]
PR in lotus: https://github.com/filecoin-project/lotus/pull/12119
I aim to make it ready for review before Monday. I would appreciate reviews on Monday there.
