### ISSUE TITLE
Design/implement power table representation

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#5]
The finality decision exchange protocol calls for a power table as a simple sequence of tuples of (ActorID, Power, PubKey), with a consistent serialization and CID. Entries are looked up by simple integer index for finality certificate validation. The table can be inflated into a map for runtime use by the protocol code.

See also #33 re truncation of power values.

```[tasklist]
### Tasks
- [ ] Implement an IPLD structure for the list-of-tuples
- [x] Add power table CID to core protocol messages
- [ ] Implement calculation of deltas between two tables, and application of deltas to a table
- [ ] #166
```

**Comment by anorth** [comment]
There's a design challenge here to make this power table feasible for verifiers running in smart contracts to compute, while also supporting compact bitfield representation of set of indices into it.

For the execution of Granite, a good representation would be a list of tuples sorted by (power descending, ID). Granite protocol messages that include explicit justification must bear a set of identifiers of the strong quorum of signers of that justification. With a power table ordered by power, we can use a bitfield of indices into that table. We might then expect long runs of small-magnitude indices (assuming that high-power miners participate most reliably) to reach a strong quorum.

Granite protocol messages carry a commitment to the resulting power table, which is then embedded in a finality certificate. The finality certificate carries deltas, but these must be verified. The naive spec is that a verifier of a finality certificate computes a new power table by applying deltas to their old table and then hashing the result, and checks that their computed has matches that. Naively, this is probably impractical (or at least unreasonably expensive) for smart contracts in some blockchain environments.
- The power table includes the public keys of all participants, which rarely change. Hashing the whole thing is 10s to 100s of KB of data
- When sorted by power, deltas that cause a change in ranking of participants would the value at many indices to change. This would confound simple merkle-tree style attempts to reduce the re-hashing

A few notes about things we can try (from discussion with @Kubuxu and @Stebalien)
- Use a commitment to a power table representation ordered by ActorID, while still using bitfield representation of sets of participants that assumes a table ordered by power. Running Granite instances can maintain both representations.
- Separate the mapping of participant public keys out from the rest of the power table, so changes in power need not re-hash the pubkey
- Use a merkle tree (or trie) representation to reduce the re-hashing to only items that have changed (and their neighbours)
- Include a commitment to the power table diff (rather than just the result) in Granite messages, so nodes reach consensus on that too
- A finality certificate could include indices of the items that a diff affects, to ease its application
- A sparse trie representation could avoid the index churn when a participant joins or leaves the table

**Comment by Stebalien** [comment]
Comparing to [CometBFT](https://github.com/cometbft/cometbft/blob/main/spec/core/data_structures.md) (@anorth pointed it out to me on Slack): Each block agrees on an entirely new committee for the next block. Effectively creating a new power table from scratch each time with no "persisted" power table.

- Benefit: Predictable and fixed size "proofs".
- Downside: Certificate verifiers need an entirely new committee each time. There may be ways to compress this information (by, e.g., remembering members of past committees), but not in a great way.

Of course, the _size_ of these proofs is why [CometBLS](https://union.build/docs/architecture/cometbls/) claims that CometBFT isn't suitable for verification on-chain. CometBFS solves(?) this by aggregating the signature part using BLS (as we do). But it's unclear if they have any way to compress the power table.

**Comment by Stebalien** [comment]
Numbers for my own use: assuming _everyone_ participates, we need ~650 of the top SPs (right now) to reach quorum.

**Comment by Stebalien** [comment]
So, I took a moment to consider _not_ storing the power table on-chain. That is:

1. Store a list of SPs and their keys on-chain.
2. Stamp the power table into every finality certificate.
3. Upload the parts of the power table we need for each epoch.

This isn't actually insane:

1. We technically only need ~25% of the power table (~650/3000) given exponential nature of the power distribution.
2. If we keep the power table off-chain, it's much simpler to [truncate](https://github.com/filecoin-project/go-f3/issues/33)/scale power (because we can just re-compute the relative powers every epoch). Really, we could just store every power value as 2 bytes (or less) of "relative" power (i.e., fraction of the total power).

That means:

1. The entire power table could likely be < 10KiB (6KiB on the current network) by just concatenating 2-byte powers, assuming we store the keys and miner IDs on-chain (which shouldn't change very often).
2. We might be able to get away with uploading only a quarter of that (1.2KiB) each time.

Unfortunately, I'm not a fan of this solution for a few reasons:

1. To get the power table down to 1.2KiB, we'd need to sort the power table by power so we can efficiently send a partial merkle-tree. If the order is random, we'd have to send most of the merkle-tree.
2. Power deltas between epochs should generally be much smaller than even the most optimized "don't store the power table on-chain" solution.

On the other hand, it really depends on how expensive on-chain writes are. If on-chain writes are expensive... this might still be a good way to go. Or, at a minimum, it might be a good idea to include this kind of "compressed" power table along with whatever else we end up including.

**Comment by anorth** [comment]
We resolved in sync discussion to _not_ target smart contract verifiers for this initial release. Some of the techniques mentioned [above](https://github.com/filecoin-project/go-f3/issues/5#issuecomment-1930769053) may still be relevant to a good, efficient, future-proof format for light clients, but we won't assume extremely limited compute or expensive storage of an L1 smart contract.

**Comment by Stebalien** [comment]
Current thoughts: https://www.notion.so/pl-strflt/F3-Commitment-Tree-Structure-d4dfc762a53a4c16a6afe2f9165b2c96

**Comment by Kubuxu** [comment]
See also https://github.com/filecoin-project/go-f3/issues/166
