### ISSUE TITLE
Unit tests for pieces of the GossipPBFT implementation

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#9]
Implement direct unit tests for the GossiPBFT code and components, independent of its exercise in simulation.
```[tasklist]
### Tasks
- [x] Signing and signature verification of received messages
- [x] Equivocations
- [x] Ignoring invalid and/or unjustified messages
- [x] Tickets for CONVERGE are weighted by power
- [x] Repetitions of a message in any phase makes no difference to outcome
- [x] Panic receiving message signed by self (but not if signature is invalid) (See https://github.com/filecoin-project/go-f3/pull/201#issuecomment-2103270975)
- [x] Tests for each step transition, by timeout and/or by receiving messages
- [x] Test skipping rounds, including from queued messages for instance
- [x] Tests for receiving messages for future rounds and validating/queuing appropriately
- [x] Test for late-arriving COMMIT that produces decision
- [x] Tests for early-arriving DECIDE
- [x] Early exit from prepare/commit when strong quorum not possible (don't need to receive more messages or alarm)
- [x] Queue messages for future rounds before finishing one (including invalid ones)
- [x] Receiving bad CIDs and TipSets in chain values
- [x] Test behaviour under boundary condition of exactly ⅓:⅔ power split
- [x] Messages from self don't arrive immediately (especially racing with alarms)
```

**Comment by masih** [comment]
> Panic receiving message signed by self (but not if signature is invalid)

Ticking this off as per discussion in https://github.com/filecoin-project/go-f3/pull/201#issuecomment-2103270975 and the separate issue that exists for it.

**Comment by masih** [comment]
> Tests for each step transition, by timeout and/or by receiving messages

Done as part of https://github.com/filecoin-project/go-f3/pull/359

**Comment by rjan90** [comment]
@masih Can we get an updated on which unit tests we have implemented, so that we have a clear what is left?

**Comment by masih** [comment]
The task list above is up-to-date already. I will prioritise the rest this week.
